const ACTION_TYPES = {
    ADD_ITEM: "ADD_ITEM",
    DELETE_ITEM: "DELETE_ITEM",
    UPDATE_ITEM: "UPDATE_ITEM",
    COMPLETE_ITEM: "COMPLETE_ITEM",
    CONFIRM_DELETE: "CONFIRM_DELETE",
    TOGGLE_THEME: "TOGGLE_THEME"
};

export default ACTION_TYPES;